### ISSUE TITLE
Bundle IIFE ES5 module

### ISSUE THREAD

**Issue by garygreen** [three11/infinite-scroll#5]
Just came across this great library, I'm looking to use it in our site to replace another library that relies on jQuery.

Though I noticed the compiled dist version is packaged with webpack and has a huge amount of bloat because of the way it's been packaged. I realise you can just import it directly and package it yourself, but personally I'm not yet using babel so I would have to add that into my webpack just to import it and support non ES6 browsers.

So would it be possible to compile a basic IIFE ES5 version? I'm not sure what the Webpack equivalent of IIFE is, I use that terminology from Rollup it's the default type when creating a library intended for the browser.

Currently this library is using UMD which isn't needed in the browser, and not needed if your using a modern bundler either, like Webpack or Rollup to consume the library.

Thanks for the consideration ! 😄

**Comment by scriptex** [comment]
The current build script utilizes the UMD pattern and creates a single IIFE for all environments. I am using this approach in all of my projects.

The bloat code that you mention comes from another external dependency which this module relies on. Since the external dependency also uses Webpack, the "bloat" is kind-of duplicated. 

I always serve minified and gzipped bundles, so this does not bother me.

I am not familiar with Rollup, but I am open for suggestions on how to improve this and keep the dependency bundled.

I will try to think of a solution which does not break the current implementation, but I currently have no free time for this.

Thanks for the understanding! 😄

**Comment by scriptex** [comment]
This is now implemented in the latest release.
For more info, refer to this commit: 7e88277aac71182b29ec6d903845c7b4a50c88c1
Thanks for your patience!
